# Generated by Django 4.2.13 on 2024-05-11 16:14

from django.db import migrations, models
import issuetracker.form_validators


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[issuetracker.form_validators.StatusValidator('.,:;?!/()[]{}')]),
        ),
    ]
