# Generated by Django 4.2.13 on 2024-05-11 20:21

from django.db import migrations, models
import issuetracker.form_validators


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[issuetracker.form_validators.validate_language], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=100, validators=[issuetracker.form_validators.validate_language, issuetracker.form_validators.check_len], verbose_name='Заголовок'),
        ),
    ]
