# Generated by Django 4.2.13 on 2024-06-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0013_project_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
    ]
