# Generated by Django 4.2.13 on 2024-05-31 18:52

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts.managers.AccountManager()),
            ],
        ),
    ]
